export const GET_FEMINISTS = 'GET_FEMINISTS';

// AUTH
export const GET_USER = 'GET_USER';
export const CREATE_USER = 'CREATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER = 'LOGIN_USER';

// POSTS
export const CREATE_POST = 'CREATE_POST';
export const GET_POSTS = 'GET_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const INCREASE_LIKE = 'INCREASE_LIKE';

// CONVERSATIONS
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';

// MESSAGES

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
